services:
  girls-side-analysis-nextjs:
    image: docker:latest
    container_name: girls-side-analysis-dood
    #environment:
    #  DOCKER_BUILDKIT: 0
    env_file:
      - .env.production
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app
    tmpfs:
      - /app/.next
    command: >
      docker build
        --network host
        -t girls-side-analysis-nextjs
        -f Dockerfile.nextjs.prod .
    network_mode: host
    
