//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "Votes")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub twitter_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub voted_time: DateTimeUtc,
    #[sea_orm(primary_key, auto_increment = false)]
    pub character_name: String,
    pub level: u8,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::characters::Entity",
        from = "Column::CharacterName",
        to = "super::characters::Column::Name",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Characters,
}

impl Related<super::characters::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Characters.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
