//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

pub use super::characters::Entity as Characters;
pub use super::user_states::Entity as UserStates;
pub use super::user_states_master::Entity as UserStatesMaster;
pub use super::votes::Entity as Votes;
