FROM node:20-slim

WORKDIR /workspace/next

RUN npm install -g pnpm

# monorepo root
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml /workspace/
# monorepo server-ts
COPY server-ts/package.json server-ts/tsconfig.json /workspace/server-ts/
# nomorepo next
COPY next/package.json next/tsconfig.json /workspace/next/

RUN pnpm install

CMD ["pnpm", "dev"]

