openapi: 3.1.0
info:
  title: server
  description: ''
  license:
    name: ''
  version: 0.1.0
paths:
  /characters:
    get:
      tags:
      - handlers
      operationId: get_characters
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CharacterDto'
components:
  schemas:
    CharacterDto:
      type: object
      required:
      - name
      - series
      - sort
      properties:
        name:
          type: string
        series:
          type: integer
          format: int32
          minimum: 0
        sort:
          type: integer
          format: int32
          minimum: 0
tags:
- name: Gril's side analysis APIs
  description: ときめきメモリアルGirl's side分析ファンサイト用APIエンドポイント
