FROM node:20-slim AS build

WORKDIR /app

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml esbuild.config.ts ./
RUN pnpm install

COPY ./src/ ./src/

RUN pnpm build


FROM gcr.io/distroless/nodejs20:debug

WORKDIR /app

COPY ./package.json ./
COPY --from=build /app/dist/index.js /app/index.js
CMD ["index.js"]

